### ISSUE TITLE
User guide document structure

### ISSUE THREAD

**Issue by rolandoisidoro** [Enalean/tuleap-documentation-en#187]
Hi,

Tuleap's documentation is growing with the tool and as it grows it's getting more difficult to find information regarding any given topic.

The User guide section is where this is most visible, since it currently has 41 topics, but lacks any perceivable structure. The screenshot bellow shows the current state of the User guide menu. Given this scenario, I often find that even alphabetical ordering the menu entries would help to some extent.

![image](https://user-images.githubusercontent.com/1101532/68497640-f0dce580-024c-11ea-95c9-281c813de7e5.png)

My experience with Tuleap, tells me that the desirable structure for me would be to map the platform's own structure, reducing 2nd level topics, grouping them by  services when possible, something like:

- Project management;
  - Dashboard
  - Administration;
    - Details;
    - Members;
    - ...;
    - Data;
    - Banner.
- Lists management;
- ...;
- Trackers management;
- Agile board management.

**Comment by rolandoisidoro** [comment]
I've spent sometime playing around with the user guide structure. Here are some preview screens of what I had in mind:

All collapsed | Inside Getting started | Inside Projects management
:--------------:|:------------------------:|:-------------------------------:
![image](https://user-images.githubusercontent.com/1101532/69265289-e6153f80-0bc0-11ea-9e26-45595880b091.png) | ![image](https://user-images.githubusercontent.com/1101532/69264972-48217500-0bc0-11ea-8783-3aef7e88d51a.png)  |  ![image](https://user-images.githubusercontent.com/1101532/69265048-69826100-0bc0-11ea-9c78-9624d9dfd5e8.png)

These are the visible changes on these examples:
- User guide and Installation guide move from being a page with a long `toctree` to being a label on the left side navigation;

- The topics on User guide are grouped in subsections, in the end we could have something like 10 or less subsections instead of the 41 topics;

- The new subsections are accessible right from the start, allowing the visitors to access the topic of their choice directly, saving clicks when navigating between sections;

- The new subsections are visible all the time, allowing the visitors to get a better overview of Tuleap's features.

Still WIP, all feedback is welcomed!

**Comment by yannis-rossetto** [comment]
Hello @rolandoisidoro 

First of all thanks for the time spent on working on the Tuleap documentation and for your feedbacks. :+1: 

Your proposal sounds promising. You can also propose your change with a pullrequest so that we can try in "real" your proposal and its evolution.

**Comment by nterray** [comment]
For your information we decreased the number of top level sections in user guide from 41 to 14. It should be better.

**Comment by rolandoisidoro** [comment]
It already looks much better. Sorry I wasn't able to contribute more.
