### ISSUE TITLE
To modify script_files in the theme is deprecated.

### ISSUE THREAD

**Issue by nterray** [Enalean/tuleap-documentation-en#266]
When I run `make html`, I get this warning:

> tuleap-documentation-en/venv/lib/python3.6/site-packages/sphinx_rtd_theme/search.html:21: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.

**Comment by LeSuisse** [comment]
This is fixed upstream, we need to wait on a release.

readthedocs/sphinx_rtd_theme#725
readthedocs/sphinx_rtd_theme#728


That's being said we have the same issue on our own tuleap.org theme.
